### PR TITLE
Add testing styleguide

### PR DESCRIPTION
**Pull request by malcolmbaig**
## Context

We could do with some basic guidelines on how we test this application.

## Changes proposed in this pull request

Add in a styleguide doc, ripping off the one from https://github.com/DFE-Digital/apply-for-teacher-training/blob/main/docs/testing-styleguide.md

## Guidance to review

Are these guidelines ok? Is there anything you'd add/remove?
## Link to Trello card

https://trello.com/c/coBfXvDo
## Things to check

- [x] This code does not rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency

### CODE REVIEW

**Comment by gpeng** [comment]
We just added page objects on Apply 4 QTS (and breaking a few of those guidelines like the parameterised step one). They use them on register too and it seems a pretty nice pattern for centralising all the binding to markup and CSS for system/feature specs. Up to you if you want to use them in this repo but worth considering. https://github.com/DFE-Digital/apply-for-qualified-teacher-status/tree/main/spec/support/autoload/page_objects

**Comment by tvararu** [comment]
> We just added page objects on Apply 4 QTS (and breaking a few of those guidelines like the parameterised step one). They use them on register too and it seems a pretty nice pattern for centralising all the binding to markup and CSS for system/feature specs. Up to you if you want to use them in this repo but worth considering. https://github.com/DFE-Digital/apply-for-qualified-teacher-status/tree/main/spec/support/autoload/page_objects

I'm in favour of this since this is a new project and it would make things more consistent / help with skill transfer between repos.

**Review by tvararu — APPROVED** [review]
I need this in Find :joy:

**Comment by malcolmbaig** [comment]
Thanks @gpeng — will likely lift some of that work if we try them out here. Will make a few amendments to this guide then.

**Pull request merged**
